import type { Metadata } from "next";
import { Inter } from "next/font/google";

/**/
//import "@/app/_styles/font.css"
import "@/app/_styles/globals.css"
//import "@/app/_styles/reset.css"
//import "@/app/_styles/animation.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "홈페이지 타이틀",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="ko">
        <body className={inter.className}>
          <div className="bg-zinc-50 min-h-[100vh]">
            <div className="flex">
              <div className="w-full flex flex-col items-center font-spoqa overflow-hidden">
                {children}
              </div>
            </div>
          </div>
        </body>
      </html>
    
  );
}