name: Deploy AWS

on:
  push:
    branches:
      - master # master 브런치로 push 시 실행
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name : checkout source code
        uses : actions/checkout@v4
      - name: Check Node v
        run: node -v
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: zip create 
        run: zip -qq -r ./kdh_ec2s3cd.zip ./.next/ ./appspec.yml ./deploy.sh # 실행파일 압축
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3 # 압축파일 S3 업로드
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./kdh_ec2s3cd.zip s3://kdh-ec2s3-bucket/kdh_ec2s3cd.zip
      - name: Deploy # CodeDeploy 사용하여 S3 -> EC2 로 업로드
        run: aws deploy create-deployment
          --application-name kdh_ec2s3cd
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --file-exists-behavior OVERWRITE
          --deployment-group-name kdh_ec2s3cd_group
          --s3-location bucket=kdh-ec2s3-bucket,key=kdh_ec2s3cd.zip,bundleType=zip